### ISSUE TITLE
Distance to value in raster instead of to shapefile

### ISSUE THREAD

**Issue by ViriatoII** [sgoodm/python-distance-rasters#17]
Hey,

This package looks awesome! Is it possible to calculate distance to a pixel value in other raster? 

For example, I have this binary raster of values 0/255. I'd like to calculate distance to 255 values:

![image](https://user-images.githubusercontent.com/25958099/131990235-29e80d89-ec4b-488c-922b-814ba4badfca.png)

It looks like it should be easy, since you transform any shapefile into a binary raster already, I just don't know what "rv_array and affine" should be then.

Cheers,
Ricardo

**Comment by sgoodm** [comment]
Hey @ViriatoII,

Yes, you absolutely use an existing raster.  The `rv_array` and `affine` would be defined along the lines of:

```
import rasterio
with rasterio.open("your_raster.tif") as src:
    affine = src.transform()
    rv_array = src.read(1)
```

I'll add an example to the repo based on this approach for other folks to reference in the future. Thanks!

**Comment by ViriatoII** [comment]
That's great, thank you! 2 things:

- **src.transform()**  gives a "not callable" error with those parenthesis, it works without them.

- Further down the line I get a math error:
```
~/.local/lib/python3.8/site-packages/distancerasters/main.py in _calculate_distance(self)
     97 
     98                     else:
---> 99                         km_min_dist = calc_haversine_distance(
    100                             convert_index_to_coords(cur_index, self.affine),
    101                             convert_index_to_coords(min_index, self.affine),

~/.local/lib/python3.8/site-packages/distancerasters/utils.py in calc_haversine_distance(p1, p2)
    243         * math.sin(delta_lon / 2) ** 2
    244     )
--> 245     c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    246     # km
    247     d = radius * c

ValueError: math domain error
```

Maybe this is an issue to open in distancerasters, but just to make sure, does this affine and rv_array look good?

```
Affine: 
 | 1.00, 0.00, 0.00|
| 0.00, 1.00, 0.00|
| 0.00, 0.00, 1.00|
rv_array: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]                                 # There are values of 255 here but they are a minority
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
```

My coordinates vary between 0 and 15,000   (It's not geography but cellular data)

Cheers.
Ricardo

**Comment by sgoodm** [comment]
Ah, yes the current implementation will always apply haversine distance calculations if an affine is provided and assumes it is just geographic, unprojected data.  I would definitely like to improve this approach to work with other types of data and be a bit more intuitive.

A quick fix that may work for your case is to not provide an `affine` or `output_path` (e.g., just `dr.DistanceRaster(rv_array)`) in order to avoid [the block of code](https://github.com/sgoodm/python-distance-rasters/blob/master/src/distancerasters/main.py#L106) using the haversine calc. You would just need to save the resulting distance array yourself using the [`export_raster` function](https://github.com/sgoodm/python-distance-rasters/blob/master/src/distancerasters/utils.py#L134) since the DistanceRaster class requires an affine in order to export as a raster.

**Comment by ViriatoII** [comment]
Hey, thank you for the help. The function runs now but unfortunately after 2 hours it still hasn't finished. Perhaps my raster is too big (195 MB)?

**Comment by sgoodm** [comment]
What are your raster dimensions? Finer-resolution data over large areas are likely to take some time, and unfortunately will definitely be slower based on Python than Java. 

I would like to produce some detailed performance/timing metrics in the future, but for now the best I can say is that I have produced a global ~1km resolution distance raster which also took around a few hours.

**Comment by ViriatoII** [comment]
Hey @sgoodm 

I was trying with a file that had 13080x15696 pixels (my analysis is at pixel resolution). Now I'm using the function on subsets of the data and it works beautifully. 

I work in spatial transcriptomics in intra- and inter-cellular space. So here you have RNA and their distance to the nucleus of the cell.


![image](https://user-images.githubusercontent.com/25958099/132724585-84deb5c4-3668-401c-b8c7-df2bf7369754.png)


With that I close the issue, thank you!

Ricardo
