### ISSUE TITLE
Make a class

### ISSUE THREAD

**Issue by jacobwhall** [sgoodm/python-distance-rasters#5]
In the future, we might want to make this package into a class of functions. This would make it easier for people to get started using this package, and get the behavior they need with fewer function calls

**Comment by sgoodm** [comment]
Note: this would almost certainly not be backwards compatible

**Comment by sgoodm** [comment]
Implemented this in develop branch b3dd37523d7cc71258832681e75e63289e0a3e61

**Comment by sgoodm** [comment]
Resolved by #15
